dist: trusty
sudo: required

os: osx
osx_image: xcode10.1

language:
  - c
  
compiler:
  - gcc
  
before_install:
  - sudo port install glew +universal
  - sudo port install libsdl2 +universal
    
script:
  - mkdir BUILD
  - cd BUILD
  - cmake ..
  - make
