dist: trusty
sudo: required

os: osx
osx_image: xcode10.1

language:
  - c
  
compiler:
  - gcc
  
before_install:
  - brew install glew
    
script:
  - mkdir BUILD
  - cd BUILD
  - cmake ..
  - make
