dist: trusty
sudo: required

language:
  - c
  
compiler:
  - gcc
  
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y  libsdl2-dev
  
script:
  - mkdir BUILD
  - cd BUILD
  - cmake ..
  - make