dist: trusty
sudo: required

os: osx
osx_image: xcode9.4

language:
  - cpp
  
compiler:
  - gcc
  
before_install:
  - brew install glew
  - brew install sdl2
  
env:
  - CXXFLAGS="-std=c++11"
    
script:
  - mkdir BUILD
  - cd BUILD
  - cmake ..
  - make
