dist: trusty
sudo: required

language:
  - cpp
  
compiler:
  - gcc
  
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libegl1-mesa-dev:i386
  - sudo apt-get install -y libgles2-mesa-dev:i386
  - sudo apt-get install -y libsdl2-dev:i386
  - sudo apt-get install -y libglew-dev:i386
  - sudo apt-get install -y libc6-dev:i386

env:
  - CXXFLAGS="-std=c++11"
    
script:
  - mkdir BUILD
  - cd BUILD
  - cmake ..
  - make
