dist: trusty
sudo: required

os: osx
osx_image: xcode9.4

language:
  - c
  
compiler:
  - gcc
  
before_install:
  - ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null
  - brew install glew
  - brew install sdl2
    
script:
  - mkdir BUILD
  - cd BUILD
  - cmake ..
  - make
