version: 1.0.{build}

branches:
  only:
  - master
#  - appveyor
  - appveyor-testbranch
  - appveyor-ubuntu
  
skip_tags: true

image: Ubuntu

configuration:
- Debug
- Release

clone_folder: c:\projects\TOMB5
#lib_folder: %clone_folder%\EXTERNAL

build:
  project: c:\projects\TOMB5\BUILD\TOMB5.sln
  verbosity: minimal
  
platform:
  - Win32
  #- x64
  
install:
  - cmd sudo apt-get update -qq
  - cmd sudo apt-get install -y libegl1-mesa-dev
  - cmd sudo apt-get install -y libgles2-mesa-dev
  - cmd sudo apt-get install -y libsdl2-dev
  
before_build:
  - cmd: mkdir BUILD
  - cmd: cd BUILD
  - cmd: make
   
artifacts:
   - path: BUILD\SPEC_PSXPC\*.zip
     name: Binaries
  
after_build:
  - cmd: cd SPEC_PSXPC
  - 7z a TOMB5.zip "%configuration%\"
  
#build: off
