version: 1.0.{build}

branches:
  only:
  - master
#  - appveyor
  - appveyor-testbranch
  - appveyor-ubuntu
  
skip_tags: true

image: Ubuntu

configuration:
- Debug
- Release

#lib_folder: %clone_folder%\EXTERNAL




platform:
  - Win32
  #- x64
  
install:
  - sh: sudo apt-get update -qq
  - sh: sudo apt-get install -y libegl1-mesa-dev
  - sh: sudo apt-get install -y libgles2-mesa-dev
  - sh: sudo apt-get install -y libsdl2-dev
  
build_script:
  - sh: mkdir BUILD
  - sh: cd BUILD
  - sh: cmake ..
  - sh: make
   
artifacts:
   - path: BUILD\SPEC_PSXPC\*.zip
     name: Binaries
  
after_build:
  - sh: ls
  - sh: cd SPEC_PSXPC
  - sh: ls
  - sh: 7z a TOMB5.zip MAIN
#  - sh: 7z a TOMB5.zip "%configuration%\"
  
#build: off
