version: 1.0.{build}

branches:
  only:
  - master
#  - appveyor
  - appveyor-testbranch
  - appveyor-ubuntu
  
skip_tags: true

image: Ubuntu

configuration:
- Debug
- Release

#lib_folder: %clone_folder%\EXTERNAL

platform: x86
  
install:
  - sh: sudo apt-get update -qq
  - sh: sudo apt-get install -y libegl1-mesa-dev
  - sh: sudo apt-get install -y libgles2-mesa-dev
  - sh: sudo apt-get install -y libsdl2-dev
  - sh: sudo apt-get install -y libglew-dev
  
before_build:
  - sh: export CXXFLAGS=-std=c++11
  - cmd: cd %clone_folder%
  #- cmd: dir /s
  - cmd: md BUILD
  - cmd: cd BUILD
  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 15 2017
  - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 15 2017 Win64
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% -DDART_MSVC_DEFAULT_OPTIONS="%MSVC_DEFAULT_OPTIONS%" ..
  
build_script:
  - sh: mkdir BUILD
  - sh: cd BUILD
  - sh: cmake ..
  - sh: make
   
artifacts:
   - path: BUILD\SPEC_PSXPC_N\*.zip
     name: Binaries
  
after_build:
  - sh: cd SPEC_PSXPC_N
  - sh: 7z a TOMB5.zip MAIN
#  - sh: 7z a TOMB5.zip "%configuration%\"
  
#build: off
