version: 1.0.{build}

branches:
  only:
  - appveyor
  
skip_tags: true

image: Visual Studio 2017

configuration:
- Debug
- Release

clone_folder: c:\projects\TOMB5

build:
  verbosity: minimal
  
platform:
  - Win32
  #- x64
  
before_build:
  - cmd: cd c:\projects\TOMB5
  - cmd: md BUILD
  - cmd: cd BUILD
  
  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 15 2017
  - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 15 2017 Win64
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% -DDART_MSVC_DEFAULT_OPTIONS="%MSVC_DEFAULT_OPTIONS%" ..
  
artifacts:
- path: TOMB5.zip
  name: TOMB5
  
after_build:
7z a TOMB5.zip %APPVEYOR_BUILD_FOLDER%\BUILD\$(configuration)\TOMB5.EXE
  
#build: off